version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.13.14
  - dependency-name: xstate
    versions:
    - 4.17.1
